In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Basic Vector Construction

In [5]:
x = np.ones(3) # vector of ones, length 3
y = np.array((2,4,5)) # converts a tuple into an array
a = x + y # adds the vectors by element
print(a)
#likewise, we can multiply
print(4*(x))

[3. 5. 6.]
[4. 4. 4.]


## Inner Product & Norm

In [9]:
np.sum(x*y) #takes the inner product of x,y, also known as the dot product
x @ y #another way

# the norm is the metric on the vector space
np.sqrt(np.sum(x**2)) #notice similar to euclidean metric
np.linalg.norm(x) #alternative

np.float64(1.7320508075688772)

# Basic Matrices

In [12]:
# basic matrix filled with 1s and 0s

id_matrix = np.identity(3) # 3x3 identity matrix
print("Identity Matrix: ",id_matrix)
ones_matrix = np.ones((2,3)) #2x3 ones matrix, meaning it is full of ones.
print("2x3 Matrix of Ones: ", ones_matrix) # as expected

unique = np.matrix([[1,2,3], # we can make our own matrices
          [4,5,6],
          [7,8,9]])


print("A unique 3x3 matrix we made: ", unique)

sum = unique + id_matrix # you can add and subtract matrices, remember matrix algebra principles.
print("Sum operation of two matrices: ", sum)


Identity Matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2x3 Matrix of Ones:  [[1. 1. 1.]
 [1. 1. 1.]]
A unique 3x3 matrix we made:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum operation of two matrices:  [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


Likewise, we are able to modify and learn more about our matrices with these operations.

In [17]:
print("The shape of our unique matrix is: ", unique.shape) # finds the shape of the matrix,(row, column)

#we are also able to transpose and take the inverse of the matrix easily
print("Transpose of unique matrix: ", unique.T)

print("Inverse of the unique matrix: ", np.linalg.inv(unique))
# note that this operation only works with square matrices


The shape of our unique matrix is:  (3, 3)
Transpose of unique matrix:  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Inverse of the unique matrix:  [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


# Solving Linear Equations
One of the basic applications of matrix algebra is solving systems of linear equations. We are able to do this with pencil and paper, but it requires many substitutions that may be unwieldy to some. It is much more systematic with matrices, especially with code.

## Basic Exercise in Economics

If we had $q_d = Dp + h$

$$\begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9
\end{pmatrix}$$